### ISSUE TITLE
TaskとUserの関連付けについて

### ISSUE THREAD

**Issue by waruru** [elca-hub/time_schedule#4]
## 現状
TaskとUserは多対多（一人のUserが複数のTaskを持ち、一つのTaskが複数のUserを持つ）の関係になっている

## 疑問
仕様として、複数のUserでTaskを持つのであれば問題ないが、そうでないのであれば**一つのTaskは一人のUserに関連づく**ようにしたほうがいい

**Comment by elca-hub** [comment]
現在はTaskとUserは多対1になっていますが、将来的には1つのTaskに複数のUserが共有する機能を実装したいと考えており、とりあえず多対多に実装しています。

**Comment by waruru** [comment]
承知です。👍
Closeします〜
