### ISSUE TITLE
特定のURLでアクセスすると、ログインしてないのに別ユーザとして操作ができる

### ISSUE THREAD

**Issue by elca-hub** [elca-hub/time_schedule#7]
## 事象
`/users/{id}/task`について、ログインしてないユーザのidを入力してアクセスしてもはじかれない

## 原因
自分でセッション管理などを行っており、うまく認証処理を利用できていない

## 理想
`users/{id}/*`共通の認証処理を行い、その後は各々の処理を行う

## 解決法
Deviseの導入

**Comment by elca-hub** [comment]
# 発生している事象について
URL内にあるidを参照せず、sessionのidでユーザ認証を行っているため、URL内のidは認証に関係がない。つまり、idが他人のであっても、実際にはsessionに登録されているidでの処理となっている

**Comment by waruru** [comment]
初めのうちはログイン処理とかはgemで実装するのはあり👍
そのうちdeviseのソースコード読んでみると、新しい発見があって面白いかも〜

**Comment by elca-hub** [comment]
了解です！試しにdeviseを使用したブランチを作成して試してみます！

**Comment by elca-hub** [comment]
一応ある程度deviseで実装できそうなので、このまま導入してみます！何かあったらissueお願いします🙇

deviseを使用したサービスのブランチ先 -> [experiment/devise](https://github.com/elca-hub/time_schedule/tree/experiment/devise)
